### ISSUE TITLE
Mesh missing half of the triangles

### ISSUE THREAD

**Issue by elanlb** [evanw/csg.js#21]
I wrote a simple JavaScript program to convert CSG objects to THREE.js [Geometry](https://threejs.org/docs/#api/core/Geometry) objects by taking the vertices and then the faces and making THREE.js objects for them. When I run the program, it seems that I only get half of the triangles that are actually in the mesh.

Could this be something related to quadrilateral polygons or is it just that the program is skipping over half of the polygons?

I have confirmed that there are eight vertices and six faces for the cube. Should there be twelve?

[elanlb/csg.js](https://github.com/elanlb/csg.js) -> [tests/threeGeometry.js](https://github.com/elanlb/csg.js/blob/master/tests/threeGeometry.js)

**Sphere**
<img width="280" alt="screen shot 2018-01-06 at 9 12 07 am" src="https://user-images.githubusercontent.com/16440094/34642032-d266d774-f2c1-11e7-98ce-1230bf31212b.png">
<img width="287" alt="screen shot 2018-01-06 at 9 12 19 am" src="https://user-images.githubusercontent.com/16440094/34642033-d27ccfac-f2c1-11e7-9c5d-95ec8fdd1189.png">
**Cube**
<img width="398" alt="screen shot 2018-01-06 at 9 12 42 am" src="https://user-images.githubusercontent.com/16440094/34642034-d292186c-f2c1-11e7-8e28-3127dd70c50a.png">
<img width="467" alt="screen shot 2018-01-06 at 9 12 50 am" src="https://user-images.githubusercontent.com/16440094/34642035-d2a7059c-f2c1-11e7-95ae-47783d2453ba.png">

**Comment by makc** [comment]
wait, so you wrote the conversion code, but the issue goes here?

**Comment by elanlb** [comment]
I don't think it's an issue with the math in csg.js, but it could be related to the way it represents meshes.

**Comment by elanlb** [comment]
So it turns out that there actually is quadrilateral geometry in csg.js. I had to check for how many vertices there were and then make one or two faces depending on the amount. If there are four vertices, one triangle is 0-1-2 and the other one is 0-2-3.

**Comment by Ni55aN** [comment]
Polygons can have 3, 4, 5 (or maybe more) vertices, so you have to add all of them
```js 
//  little dirty code
var geometry = new THREE.Geometry();

function addFace(vertices, plane) {
  var j = geometry.vertices.length;
  var vertexNormals = [];
  
  vertices.map((v,i) => {
    geometry.vertices.push(new THREE.Vector3(v.pos.x, v.pos.y, v.pos.z));
    vertexNormals.push(new THREE.Vector3(v.normal.x, v.normal.y, v.normal.z));
  })
  var normal = new THREE.Vector3(plane.normal.x, plane.normal.y, plane.normal.z);
  geometry.faces.push(new THREE.Face3(j, j+1, j+2, normal, vertexNormals))
}

polygons.map(poly => {
  if(poly.vertices.length === 6) {
     let [a, b, c, d, e, f] = poly.vertices;
      addFace([a, b, c], poly.plane);
      addFace([c, d, e], poly.plane);
      addFace([e, f, a], poly.plane);
      addFace([a, c, e], poly.plane);
  } else if(poly.vertices.length === 5) {
     let [a, b, c, d, e] = poly.vertices;
      addFace([a, b, c], poly.plane);
      addFace([c, d, e], poly.plane);
      addFace([e, a, c], poly.plane);
  } else if(poly.vertices.length === 4) {
     let [a, b, c, d] = poly.vertices;
    addFace([a, b, c], poly.plane);
    addFace([c, d, a], poly.plane);
  } else {
      let [a, b, c] = poly.vertices;
      addFace([a, b, c], poly.plane);
  }
});
```
