### ISSUE TITLE
Touch friendly viewer

### ISSUE THREAD

**Issue by peter-hartmann** [evanw/csg.js#22]
Awesome project, allows building tools that make sharing and collaborating on 3D objects easier.  Much needed!

Any plans or efforts on making the viewer usable on touchscreen devices? 

This would be my feature request.

**Comment by RicoP** [comment]
There is literally no code commit since 6 years, so I think the answer is no :p

**Comment by z3dev** [comment]
See www.openjscad.org

**Comment by manthrax** [comment]
http://vectorslave.com/csg/CSGShinyDemo.html

**Comment by makc** [comment]
@manthrax with newer 3js you can now do [this](http://makc.github.io/three.js/csg/), which is way faster, but does not scale very well.

**Comment by manthrax** [comment]
@makc That also doesn't give you the geometry.. it's purely a stencil buffer trick. Pretty cool, but useless for actually generating new geometry.

**Comment by peter-hartmann** [comment]
https://github.com/jscad/csg-viewer
This one is touch friendly, hurray!
